# Generated by Django 3.1.1 on 2020-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(default='2020-09-29: now', max_length=64),
        ),
    ]
